// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdoi28Kar8wc0MoNUu23wo1Tr2VokIliY',
    appId: '1:570579557528:web:bab728fe782923531884ed',
    messagingSenderId: '570579557528',
    projectId: 'bookshop-project-d621a',
    authDomain: 'bookshop-project-d621a.firebaseapp.com',
    storageBucket: 'bookshop-project-d621a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAS8KxUtlg2TpYeaCvvyw_AARA9fKgYXOs',
    appId: '1:570579557528:android:f45c33edb32e66751884ed',
    messagingSenderId: '570579557528',
    projectId: 'bookshop-project-d621a',
    storageBucket: 'bookshop-project-d621a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALX3a1FnzqKgym33tZv0ZTqpjWST9gbGU',
    appId: '1:570579557528:ios:b541b834565adaa11884ed',
    messagingSenderId: '570579557528',
    projectId: 'bookshop-project-d621a',
    storageBucket: 'bookshop-project-d621a.appspot.com',
    iosBundleId: 'com.example.bookshopProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALX3a1FnzqKgym33tZv0ZTqpjWST9gbGU',
    appId: '1:570579557528:ios:ce233db6acb195311884ed',
    messagingSenderId: '570579557528',
    projectId: 'bookshop-project-d621a',
    storageBucket: 'bookshop-project-d621a.appspot.com',
    iosBundleId: 'com.example.bookshopProject.RunnerTests',
  );
}
